name = "XSteamUnits"
uuid = "8dcf7b82-35f3-4204-ad2f-e05d602ed089"
authors = [""]
version = "0.1.0"

[deps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
julia = "1.0"
Unitful = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
